# Generated by Django 5.1 on 2024-08-24 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('scoring', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='score',
            name='exam_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examroom'),
        ),
        migrations.AddField(
            model_name='score',
            name='score_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.scoreitem'),
        ),
    ]
